name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: sign apk
      uses: upup-company/apksigner-android@v1
      with:
        releaseDirectory: app/build/outputs/bundle/release
        signingKeyBase64: MTIzMTIz
        alias: key0
        keyStorePassword: ""
        keyPassword: ""
    - run: ls app/build/outputs/bundle/release
    - name: Upload App Bundle
      uses: actions/upload-artifact@v1
      with:
        name: aab
        path: ${{steps.sign_aab.outputs.signedReleaseFile}}
