name: Android CI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - uses: gradle/gradle-build-action@v2
      with:
        gradle-version: current
        arguments: assembleRelease
   

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          *.apk
