name: Auto-Release

on:
  push:
    branches:
      - master

permissions:
  contents: write # Required to create releases
  pull-requests: write # Required to create comments on the PRs

jobs:
  Auto-Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Auto-Release
        uses: PSModule/Auto-Release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }} # Used for GitHub CLI authentication