name: "pre-release"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: “${{github.run_id}}"
          title: "apk打包结果"
          prerelease: false
          files: |
            README.md